### ISSUE TITLE
为什么这个工具转的和网上在线转的不一样

### ISSUE THREAD

**Issue by HeMing505** [fankes/BitmapToBase64#2]
为什么这个工具转的和网上在线转的不一样，然后我好像也无法还原出大佬你在原生通知图标项目的图标，是有加密吗
我本来想做一个参考的，想贡献一下

**Comment by fankes** [comment]
核心代码就是[这一行](https://github.com/fankes/BitmapToBase64/blob/master/app/src/main/java/com/fankes/bitmaptobase64/MainActivity.kt#L31)，你可以自己看看，有关代码也是字节流到 <b>Bitmap</b>。
